sortkey: order
encoding: utf-8
gems:
  - github-pages
defaults:
  -
    scope:
      path: "" # an empty string means all files in the project
    values:
      layout: "default"
      publish: "true"
